import { readFileSync, existsSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { REFERENCE_ACTIVITY_FPS, REFERENCE_HUMAN_ACTIVITIES, REFERENCE_DOG_ACTIVITIES, REFERENCE_OBJECT_STATES, activityKey } from '../src/phaserMigration2ReferenceCompletion.js';
const runtime=readFileSync(new URL('../src/phaserMigration2Runtime.js',import.meta.url),'utf8');
const css=readFileSync(new URL('../styles.css',import.meta.url),'utf8');
describe('P2 reference visual completion',()=>{
  it('implements explicit 8 FPS entry loop exit activities',()=>{expect(REFERENCE_ACTIVITY_FPS).toBe(8);expect(REFERENCE_HUMAN_ACTIVITIES.length).toBeGreaterThanOrEqual(27);expect(REFERENCE_DOG_ACTIVITIES.length).toBeGreaterThanOrEqual(7);for(const key of ['cook','eat','shower','bath','toilet','sleep','cuddle','desk_work','arcade','pool','basketball','treadmill','weights','heavy_bag','swim','soccer','wash_dog','vehicle','cleaning'])expect(REFERENCE_HUMAN_ACTIVITIES).toContain(key);});
  it('maps distinct activities without a generic interact bucket',()=>{expect(activityKey({id:'resident',action:'Cooking dinner',actionT:4})).toBe('cook');expect(activityKey({id:'resident',action:'Punching heavy bag',actionT:4})).toBe('heavy_bag');expect(activityKey({id:'dog',kind:'dog',action:'Eating from dog bowl',actionT:4})).toBe('dog_eat');expect(REFERENCE_HUMAN_ACTIVITIES).not.toContain('interact');});
  it('provides complete animated object state coverage',()=>{for(const key of ['fridge_open','stove_cooking','sink_running','coffee_brewing','shower_active','bathtub_active','toilet_occupied','bed_sleeping','tv_on','desk_active','arcade_active','pool_table_active','door_open','car_open','closet_open'])expect(REFERENCE_OBJECT_STATES).toContain(key);});
  it('integrates completion into native Phaser lifecycle',()=>{expect(runtime).toContain('preloadReferenceCompletion(this)');expect(runtime).toContain('createReferenceCompletion(this)');expect(runtime).toContain('syncReferenceCompletion(this)');expect(runtime).not.toContain('drawPhaserEnvironment');expect(runtime).not.toContain('textures.addCanvas');});
  it('ships real PNG activity and state assets',()=>{expect(existsSync(new URL('../assets/phaser-migration-2/sprites/activities/cook/resident.png',import.meta.url))).toBe(true);expect(existsSync(new URL('../assets/phaser-migration-2/sprites/activities/shower/girlfriend.png',import.meta.url))).toBe(true);expect(existsSync(new URL('../assets/phaser-migration-2/sprites/activities/dog_soccer/dog.png',import.meta.url))).toBe(true);expect(existsSync(new URL('../assets/phaser-migration-2/sprites/states/fridge_open.png',import.meta.url))).toBe(true);});
  it('installs final architecture lighting foreground and UI systems',()=>{const source=readFileSync(new URL('../src/phaserMigration2ReferenceCompletion.js',import.meta.url),'utf8');expect(source).toContain('drawArchitecture');expect(source).toContain('drawLightingAndEffects');expect(source).toContain('foreground');expect(css).toContain('P2_REFERENCE_VISUAL_COMPLETION');});
});
